# Site
name: "Curl-Diaries"
title: "Curl Diaries"
description: "Hi, I made this blog to write my thoughts on curly hair products. I'll include tips, experiences, and links to buy the products :)"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Jerusha
    display_name: Jerusha
    gravatar: 0f8355ba15e237a530cdd12ba2bdc3c1
    email: jerusham55@gmail.com
    description: "Meet Jerusha, a reviewer of curly hair products, sharing insights to help those with curly hair and their unique needs."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
