# Site
name: "Curl-Diaries"
title: "Curl Diaries"
description: "Hi, I created this blog to write personal product reviews! I also have two posts dedicated to porosity. Click on any title that interests you. :)"
logo: 'assets/images/logoc-d.jpg'
favicon: 'assets/images/logoc-d.jpg'
#baseurl: /mediumish-theme-jekyll
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Jerusha
    display_name: Jerusha Manoj
    gravatar: 0f8355ba15e237a530cdd12ba2bdc3c1
    email: jerusham55@gmail.com
    description: "Hi everyone, thank you for checking out my blog. I hope you found something helpful! I want to make a disclaimer that what works for me may not work for you and vice versa. Enjoy the read!"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
